language: python

matrix:
  include:
    - stage: tests
      python: "3.6"
      name: "Unit Tests"
      script: python3 -m unittest
    - stage: tests
      python: "3.6"
      name: "Integration Test"
      script: ./getdiskusage.py ./